Repository muxinc/mux-stats-sdk-exoplayer, pull requests merged in 2022-12, with the labels that each got.

#257 Fix for ticket 46709
  ExoPlayerAdapter/src/main/java/com/mux/stats/sdk/muxstats/internal/BandwidthMetric.kt
  build.gradle
Labels: enhancement

#258 Improve Error Code Variety on ExoPlayer 2.15+
  ExoPlayerAdapter/src/exo-error-2_15-now/java/com/mux/stats/sdk/muxstats/ExoErrorMetrics215ToNow.kt
  ExoPlayerAdapter/src/exo-error-just-2_14/java/com/mux/stats/sdk/muxstats/ExoErrorMetricsUpTo214.kt
  ExoPlayerAdapter/src/exo-error-upto-2_13/java/com/mux/stats/sdk/muxstats/ExoErrorMetricsUpTo214.kt
  ExoPlayerAdapter/src/main/java/com/mux/stats/sdk/muxstats/internal/Util.kt
Labels: updates

#260 Total dropped frames
  ExoPlayerAdapter/src/exo-analytics-listener-2_11-2_13/java/com/mux/stats/sdk/muxstats/internal/ExoAnalyticsListener.kt
  ExoPlayerAdapter/src/exo-analytics-listener-2_13-2_16/java/com/mux/stats/sdk/muxstats/internal/ExoAnalyticsListener.kt
  ExoPlayerAdapter/src/exo-analytics-listener-2_18-now/java/com/mux/stats/sdk/muxstats/internal/ExoAnalyticsListener.kt
  ExoPlayerAdapter/src/exo-analytics-listener-just-2_17/java/com/mux/stats/sdk/muxstats/internal/ExoAnalyticsListener.kt
  ExoPlayerAdapter/src/exo-analytics-listener-upto-2_11/java/com/mux/stats/sdk/muxstats/internal/ExoAnalyticsListener.kt
  ExoPlayerAdapter/src/main/java/com/mux/stats/sdk/muxstats/MuxStateCollectorBase.kt
Labels: enhancement, updates
